### ISSUE TITLE
Failed to activate the git-diff-details package

### ISSUE THREAD

**Issue by patsilvia** [samu/git-diff-details#14]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.9.5
**Thrown From**: [git-diff-details](https://github.com/samu/git-diff-details) package, v0.8.0

### Stack Trace

Failed to activate the git-diff-details package

```
At undefined is not a function

TypeError: undefined is not a function
  at Object.module.exports.activate (/Users/patai/.atom/packages/git-diff-details/lib/main.coffee:7:40)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:85:18)
  at ChildProcess.emit (events.js:119:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)

```

### Commands

```
     -0:58.8 settings-view:open (a.btn-issue.btn.btn-error)
  2x -0:47.5 core:backspace (atom-text-editor.editor.mini)
  2x -0:46.5 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
git-diff-details, v0.8.0
git-log, v0.3.0
language-puppet, v0.10.0
linter-perl, v0.4.1
minimap, v4.2.2
minimap-git-diff, v4.1.2
vim-mode, v0.30.0

# Dev
No dev packages
```

**Comment by samu** [comment]
Not sure if this still is still a problem. Gonna close it for now.

**Comment by jonatassalgado** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Ubuntu 14.04.4
**Thrown From**: [git-diff-details](https://github.com/samu/git-diff-details) package, v1.3.0


### Stack Trace

Failed to activate the git-diff-details package

```
At atom.workspace.buildTextEditor is not a function

TypeError: atom.workspace.buildTextEditor is not a function
  at AtomGitDiffDetailsView.module.exports.AtomGitDiffDetailsView.initialize (/home/jonatas/.atom/packages/git-diff-details/lib/git-diff-details-view.coffee:23:34)
  at AtomGitDiffDetailsView.View (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new AtomGitDiffDetailsView (/home/jonatas/.atom/packages/git-diff-details/lib/git-diff-details-view.coffee:8:3)
  at /home/jonatas/.atom/packages/git-diff-details/lib/main.coffee:27:11
  at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:276:9)
  at Object.module.exports.activate (/home/jonatas/.atom/packages/git-diff-details/lib/main.coffee:26:20)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:245:19)
  at /usr/share/atom/resources/app.asar/src/package.js:226:30
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:169:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:218:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:486:21)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:371:29
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:60:16)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```

### Commands

```
  4x -4:42.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -4:41.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -4:35.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -4:32.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:32.6.0 git-diff:toggle-diff-list (atom-text-editor.editor)
     -4:30.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -4:30.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -4:30 core:move-down (atom-text-editor.editor.is-focused)
     -4:29.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -4:28.4.0 pane:show-next-item (atom-text-editor.editor.is-focused)
     -3:17.7.0 editor:select-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
     -3:15.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:51.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:48.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:47.8.0 merge-conflicts:detect (atom-text-editor.editor)
     -0:38.9.0 settings-view:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-monokai"
    ],
    "disabledPackages": [
      "language-vue-component",
      "jasmine-runner",
      "imdone-atom",
      "linter-coffeelint",
      "livereload",
      "meteor-api",
      "riot",
      "atom-jasmine",
      "coffee-refactor",
      "coffeescript-check",
      "git-time-machine",
      "run-in-atom",
      "sass-watch"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-monokai, v0.10.2
auto-indent, v0.5.0
autoclose-html, v0.23.0
autocomplete-html-entities, v0.1.0
autocomplete-ruby, v0.1.0
file-icons, v1.7.11
git-diff-details, v1.3.0
git-diff-popup, v0.1.8
highlight-selected, v0.11.2
js-refactor, v0.6.0
language-ruby-on-rails, v0.25.0
language-vue, v0.13.0
merge-conflicts, v1.4.3
minimap, v4.24.2
minimap-git-diff, v4.3.1
refactor, v0.6.0
saveallthetime, v0.2.1
sync-settings, v0.7.2
tree-view-git-modified, v0.6.2
vue-autocomplete, v0.1.0
you-complete-me, v0.6.5

# Dev
No dev packages
```

**Comment by samu** [comment]
@jonatassalgado your atom version is really old, have you tried an upgrade?
