### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidChangeStatuses' of undefined

### ISSUE THREAD

**Issue by asci** [samu/git-diff-details#22]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.1
**Thrown From**: [git-diff-details](https://github.com/samu/git-diff-details) package, v0.18.0

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidChangeStatuses' of undefined

```
At /Users/artem/.atom/packages/git-diff-details/lib/housekeeping.coffee:58

TypeError: Cannot read property 'onDidChangeStatuses' of undefined
  at AtomGitDiffDetailsView.module.exports.Housekeeping.subscribeToRepository (/Users/artem/.atom/packages/git-diff-details/lib/housekeeping.coffee:58:34)
  at /Users/artem/.atom/packages/git-diff-details/lib/housekeeping.coffee:22:60
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Project.module.exports.Project.addPath (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:274:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:848:41
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:409:16)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -0:56.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor)
     -0:55.7.0 core:save (atom-text-editor.editor)
     -0:46 core:close (atom-text-editor.editor.is-focused)
     -0:04.4.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "darkula-ui",
      "darkula-syntax"
    ],
    "disabledPackages": [
      "minimap-git-diff"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.24.1
atom-handlebars, v0.5.0
atom-ternjs, v0.5.23
build, v0.29.0
color-picker, v1.7.0
darkula-syntax, v0.3.0
darkula-ui, v0.1.0
ember-snippets, v1.1.3
git-diff-details, v0.18.0
language-ejs, v0.1.0
linter, v0.12.1
react, v0.11.7
refactor, v0.4.1

# Dev
No dev packages
```

**Comment by samu** [comment]
Thanks for reporting. How do i reproduce this?

This most likely happens when you open a project or file that doesn't relate to a git repo, or when opening the settings view, though i thought this was fixed.

**Comment by d0c** [comment]
Steps to reproduce:
- in directory tree right-click the folder and choose "Open in New Window"
- double-click some file to start editing it
- right-click root folder in tree view and choose "Remove Project Folder"

And that's it

**Comment by samu** [comment]
@d0c Thanks! I'll look into it.

**Comment by rm-code** [comment]
Another way to reproduce is:

1. Have a project folder with a git repository
2. Add another project folder without a git repository

**Comment by Jonanin** [comment]
I also ran into this issue the way @rm-code mentioned.

**Comment by carl-parrish** [comment]
Also seems to work the other way around. I had a project that wasn't a git repository then opened a git repository project and got it.

**Comment by samu** [comment]
This should be fixed with #22. I released it in version `v0.19.0`. I'm not sure if all edge cases are covered by this fix, so please let me know if the problem remains for you.

**Comment by pavlo-yuriychuk** [comment]
Got it
~~~javascript
/home/piuriichuk/.atom/packages/git-diff-details/lib/housekeeping.coffee:58
Hide Stack Trace
TypeError: Cannot read property 'onDidChangeStatuses' of undefined
    at AtomGitDiffDetailsView.module.exports.Housekeeping.subscribeToRepository (/home/piuriichuk/.atom/packages/git-diff-details/lib/housekeeping.coffee:107:40)
    at /home/piuriichuk/.atom/packages/git-diff-details/lib/housekeeping.coffee:42:26
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Project.module.exports.Project.addPath (/opt/atom/resources/app.asar/src/project.js:274:29)
    at /opt/atom/resources/app.asar/src/atom.js:862:41
    at EventEmitter.<anonymous> (/opt/atom/resources/app.asar/src/atom.js:412:16)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:166:7)
~~~

**Comment by Evmorov** [comment]
@pavlo-yuriychuk Are you sure that you are using the last version? What is the case?

**Comment by rm-code** [comment]
0.19.0 fixed it for me :+1:
