### ISSUE TITLE
Failed to activate the svn package

### ISSUE THREAD

**Issue by shaggybb** [samu/git-diff-details#24]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Ubuntu 14.04.2
**Thrown From**: [git-diff-details](https://github.com/samu/git-diff-details) package, v0.18.0

### Stack Trace

Failed to activate the svn package

```
At Cannot read property 'onDidChangeStatuses' of undefined

TypeError: Cannot read property 'onDidChangeStatuses' of undefined
    at AtomGitDiffDetailsView.module.exports.Housekeeping.subscribeToRepository (/home/ivan/.atom/packages/git-diff-details/lib/housekeeping.coffee:107:40)
    at /home/ivan/.atom/packages/git-diff-details/lib/housekeeping.coffee:42:26
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at Project.module.exports.Project.setPaths (/usr/share/atom/resources/app.asar/src/project.js:237:27)
    at /usr/share/atom/resources/app.asar/src/project.js:71:26
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:34)
    at ServiceHub.module.exports.ServiceHub.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:29:18)
    at Package.module.exports.Package.activateServices (/usr/share/atom/resources/app.asar/src/package.js:372:65)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:243:16)
    at /usr/share/atom/resources/app.asar/src/package.js:221:30
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:165:15)
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:213:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:452:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:436:29
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:431:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:412:46)
    at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom.js:645:21)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/window-bootstrap.js:12:8)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/window-bootstrap.js:23:4)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:96:23)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:36:7)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.18.0
code-links, v0.3.11
git-diff-details, v0.18.0
linter, v1.2.3
linter-htmlhint, v0.0.17
linter-jshint, v0.1.7
minimap, v4.11.0
minimap-autohide, v0.10.0
minimap-bookmarks, v0.1.0
minimap-git-diff, v4.1.4
minimap-linter, v1.0.0
svn, v0.0.6

# Dev
No dev packages
```

**Comment by samu** [comment]
Thanks for reporting. 
Duplicate to #22
