### ISSUE TITLE
Uncaught Error: Repository has been destroyed

### ISSUE THREAD

**Issue by bisraelsen** [samu/git-diff-details#28]
[Enter steps to reproduce below:]

1. Open up project folder

**Atom Version**: 1.0.4
**System**: Ubuntu 14.04.3
**Thrown From**: [git-diff-details](https://github.com/samu/git-diff-details) package, v0.19.0

### Stack Trace

Uncaught Error: Repository has been destroyed

```
At /usr/share/atom/resources/app.asar/src/git-repository.js:382

Error: Repository has been destroyed
  at GitRepository.module.exports.GitRepository.getRepo (/usr/share/atom/resources/app.asar/src/git-repository.js:382:15)
  at DiffDetailsDataManager.module.exports.DiffDetailsDataManager.prepareLineDiffDetails (/home/brett/.atom/packages/git-diff-details/lib/data-manager.coffee:45:17)
  at DiffDetailsDataManager.module.exports.DiffDetailsDataManager.updateLineDiffDetails (/home/brett/.atom/packages/git-diff-details/lib/data-manager.coffee:37:8)
  at DiffDetailsDataManager.module.exports.DiffDetailsDataManager.getSelectedHunk (/home/brett/.atom/packages/git-diff-details/lib/data-manager.coffee:15:8)
  at AtomGitDiffDetailsView.module.exports.AtomGitDiffDetailsView.updateDiffDetailsDisplay (/home/brett/.atom/packages/git-diff-details/lib/git-diff-details-view.coffee:114:61)
  at AtomGitDiffDetailsView.module.exports.AtomGitDiffDetailsView.updateDiffDetails (/home/brett/.atom/packages/git-diff-details/lib/git-diff-details-view.coffee:60:6)
  at AtomGitDiffDetailsView.module.exports.AtomGitDiffDetailsView.toggleShowDiffDetails (/home/brett/.atom/packages/git-diff-details/lib/git-diff-details-view.coffee:64:6)
  at atom-text-editor.<anonymous> (/home/brett/.atom/packages/git-diff-details/lib/housekeeping.coffee:25:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -0:00.9.0 git-diff-details:toggle-git-diff-details (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "sublime-tabs",
      "vim-mode"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
atom-julia, v0.2.0
atom-python-debugger, v0.3.4
autocomplete-paths, v1.0.2
autocomplete-plus-python-jedi, v0.3.6
file-icon-supplement, v0.8.3
file-icons, v1.6.2
git-diff-details, v0.19.0
git-tab-status, v1.9.2
language-latex, v0.6.1
language-matlab, v0.1.1
latex, v0.25.0
line-ending-converter, v1.2.0
linter, v1.3.1
linter-flake8, v1.6.0
linter-python-pep8, v0.2.0
minimap, v4.12.2
minimap-git-diff, v4.1.7
pdf-view, v0.23.0
project-ring, v0.33.2
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by samu** [comment]
@bisraelsen Thanks. How do i reproduce this?

**Comment by samu** [comment]
Closing this due to inactivity, feel free to reopen if the problem persists.
