### ISSUE TITLE
Failed install - oniguruma

### ISSUE THREAD

**Issue by mishak87** [samu/git-diff-details#3]
Failes to install due to oniguruma.

```
> oniguruma@3.0.5 install /tmp/apm-install-dir-115012-13039-qwrf7t/node_modules/git-diff-details/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma
> node-gyp rebuild

make: Entering directory `/tmp/apm-install-dir-115012-13039-qwrf7t/node_modules/git-diff-details/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma/build'
  CC(target) Release/obj.target/oniguruma/deps/onig/regcomp.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regenc.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regerror.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regexec.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regext.o
  CC(target) Release/obj.target/oniguruma/deps/onig/reggnu.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regparse.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regposerr.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regposix.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regsyntax.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regtrav.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regversion.o
  CC(target) Release/obj.target/oniguruma/deps/onig/st.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/ascii.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/big5.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/cp1251.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_jp.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_kr.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_tw.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/gb18030.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_1.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_2.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_3.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_4.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_5.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_6.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_7.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_8.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_9.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_10.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_11.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_13.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_14.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_15.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_16.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8_r.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/mktable.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/sjis.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/unicode.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_be.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_le.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_be.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_le.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf8.o
  AR(target) Release/obj.target/oniguruma.a
  COPY Release/oniguruma.a
  CXX(target) Release/obj.target/onig_scanner/src/onig-cache.o
make: Leaving directory `/tmp/apm-install-dir-115012-13039-qwrf7t/node_modules/git-diff-details/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma/build'

npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/highlights/0.14.0
npm http 304 https://registry.npmjs.org/mixto
npm http 304 https://registry.npmjs.org/highlights/0.14.0
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/fs-plus
npm http GET https://registry.npmjs.org/first-mate
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 200 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/fs-plus
npm http 304 https://registry.npmjs.org/first-mate
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/grim
npm http 304 https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/event-kit
npm http GET https://registry.npmjs.org/oniguruma
npm http GET https://registry.npmjs.org/season
npm http 200 https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/wordwrap
npm http 200 https://registry.npmjs.org/season
npm http 304 https://registry.npmjs.org/grim
npm http 304 https://registry.npmjs.org/oniguruma
npm http 304 https://registry.npmjs.org/emissary
npm http 304 https://registry.npmjs.org/event-kit
npm http GET https://registry.npmjs.org/coffeestack
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/property-accessors
npm http 304 https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/nan/1.2.0
npm http 304 https://registry.npmjs.org/coffeestack
npm http GET https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/amdefine
npm http 304 https://registry.npmjs.org/nan/1.2.0
make: g++: Command not found
make: *** [Release/obj.target/onig_scanner/src/onig-cache.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.13.0-43-generic
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-115012-13039-qwrf7t/node_modules/git-diff-details/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm ERR! oniguruma@3.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@3.0.5 install script.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-43-generic
npm ERR! command "/usr/share/atom/resources/app/apm/node_modules/atom-package-manager/bin/node" "/usr/share/atom/resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/usr/share/atom/resources/app/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/home/mishak/.atom/.apmrc" "install" "/home/mishak/.atom/.node-gyp/.atom/.apm/git-diff-details/0.5.0/package.tgz" "--target=0.18.0" "--arch=x64"
npm ERR! cwd /tmp/apm-install-dir-115012-13039-qwrf7t
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /tmp/apm-install-dir-115012-13039-qwrf7t/npm-debug.log
npm ERR! not ok code 0
```

**Comment by samu** [comment]
How can i reproduce this?

**Comment by mishak87** [comment]
I tried to install on other Ubuntu PC and it worked but on this one it still fails. It might be an issue with ELIFECYCLE

**Comment by samu** [comment]
Ok, so i'm assuming this has something to do with your node installation on your other PC, so i'll close this for now.

**Comment by mishak87** [comment]
On both pcs I am installing from web8 repository (using deb packages) I have not installed node AFAIK.

**Comment by schotime** [comment]
I get this issue on windows on v0.174.0.
