### ISSUE TITLE
Failed to load the git-diff-details package

### ISSUE THREAD

**Issue by josephdburdick** [samu/git-diff-details#35]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [git-diff-details](https://github.com/samu/git-diff-details) package, v0.21.0

### Stack Trace

Failed to load the git-diff-details package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/jb/.atom/packages/git-diff-details/node_modules/highlights/lib/highlights.js:6:7)
    at Object.<anonymous> (/Users/jb/.atom/packages/git-diff-details/node_modules/highlights/lib/highlights.js:419:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/jb/.atom/packages/git-diff-details/lib/git-diff-details-view.coffee:3:14)
    at Object.<anonymous> (/Users/jb/.atom/packages/git-diff-details/lib/git-diff-details-view.coffee:1:1)
    at Module._compile (module.js:428:26)
```

### Commands

```
     -0:03.0 tree-view:toggle (div.panels-item)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "wrap-guide",
      "language-javascript-jsx"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jasmine, v0.6.0
atom-lorempixel, v0.1.0
autocomplete-modules, v1.3.1
emmet, v2.3.14
git-diff-details, v0.21.0
indent-guide-improved, v1.4.3
jsformat, v0.9.0
jshint, v1.8.3
language-babel, v1.0.0
react, v0.12.10
react-snippets, v0.2.0
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by samu** [comment]
Maybe the package dependencies didn't install properly. Try running these commands at the root of the `git-diff-details` package:

`apm install`
`apm rebuild`

**Comment by josephdburdick** [comment]
Did that, restarted, left with the same issue. 

Moved to the highlights package, ran the same `apm install; apm rebuild` restarted Atom, and it booted up without issue. Thanks.
