### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by graydori** [samu/git-diff-details#61]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [git-diff-details](https://github.com/samu/git-diff-details) package, v1.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of null

```
At /Users/shan.naziripour/.atom/packages/git-diff-details/lib/data-manager.coffee:90

TypeError: Cannot read property 'length' of null
    at DiffDetailsDataManager.module.exports.DiffDetailsDataManager.prepareWordDiffs (/Users/shan.naziripour/.atom/packages/git-diff-details/lib/data-manager.coffee:90:5)
    at DiffDetailsDataManager.module.exports.DiffDetailsDataManager.updateLineDiffDetails (/Users/shan.naziripour/.atom/packages/git-diff-details/lib/data-manager.coffee:40:8)
    at DiffDetailsDataManager.module.exports.DiffDetailsDataManager.getSelectedHunk (/Users/shan.naziripour/.atom/packages/git-diff-details/lib/data-manager.coffee:17:8)
    at AtomGitDiffDetailsView.module.exports.AtomGitDiffDetailsView.updateDiffDetailsDisplay (/Users/shan.naziripour/.atom/packages/git-diff-details/lib/git-diff-details-view.coffee:135:61)
    at AtomGitDiffDetailsView.module.exports.AtomGitDiffDetailsView.notifyChangeCursorPosition (/Users/shan.naziripour/.atom/packages/git-diff-details/lib/git-diff-details-view.coffee:71:8)
    at /Users/shan.naziripour/.atom/packages/git-diff-details/lib/housekeeping.coffee:20:64
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextEditor.module.exports.TextEditor.cursorMoved (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1732:27)
    at Selection.module.exports.Selection.markerDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:927:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:41:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextEditorMarker.module.exports.TextEditorMarker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:264:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:65:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:396:20)
    at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:342:12)
    at Marker.module.exports.Marker.setHeadPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:135:19)
    at TextEditorMarker.module.exports.TextEditorMarker.setHeadBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:175:32)
    at TextEditorMarker.module.exports.TextEditorMarker.setHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:185:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:67:31
    at Cursor.module.exports.Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:673:7)
    at Cursor.module.exports.Cursor.setScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:65:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1506:23
    at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1726:9)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1505:19)
    at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:730:25)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)
```

### Commands

```
     -6:08.0 project-find:show (atom-text-editor.editor.power-mode.is-focused)
     -6:07.6.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -6:07.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:33.9.0 core:copy (atom-text-editor.editor.power-mode.is-focused)
     -3:33 project-find:show (atom-text-editor.editor.power-mode.is-focused)
     -3:32.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -3:30.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:20.6.0 core:copy (atom-text-editor.editor.is-focused.power-mode)
     -1:19.9.0 project-find:show (atom-text-editor.editor.is-focused.power-mode)
     -1:19.6.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:18.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:14.2.0 core:copy (atom-text-editor.editor.power-mode.is-focused)
     -0:09.9.0 find-and-replace:show (atom-text-editor.editor.power-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2
aligner-scss, v1.1.0
atom-beautify, v0.29.7
atom-jade, v0.3.0
auto-detect-indentation, v1.0.0
auto-indent, v0.5.0
bottom-dock, v0.4.4
compare-files, v0.6.2
file-icons, v1.7.11
git-blame, v0.4.8
git-diff-details, v1.3.0
highlight-selected, v0.11.2
jade-beautify, v0.1.4
language-SCSS, v0.4.0
language-slim, v0.5.0
linter, v1.11.4
linter-jade, v0.3.2
linter-jshint, v2.1.0
linter-manager, v0.2.12
linter-ruby, v1.2.2
linter-sass-lint, v1.4.3
linter-scss-lint, v3.0.3
linter-shellcheck, v1.2.0
linter-slim, v1.0.0
merge-conflicts, v1.4.2
minimap, v4.23.5
minimap-highlight-selected, v4.4.0
minimap-pigments, v0.2.1
open-recent, v5.0.0
pigments, v0.26.2
ruby-slim, v0.2.0
seti-icons, v0.4.5
seti-syntax, v1.0.1
seti-ui, v1.1.2
slim-language, v2.2.0
you-complete-me, v0.7.4

# Dev
No dev packages
```

**Comment by samu** [comment]
thanks for reporting. do you know how to reproduce this?

**Comment by graydori** [comment]
It happened randomly on a file when toggling git-diff but i can't repo it anymore.
Sorry.

**Comment by samu** [comment]
No worries, thanks for the follow up

**Comment by jmdacruz** [comment]
I just got the same error... but it's unclear how to reproduce (seems random)

**Comment by jmdacruz** [comment]
This is what I'm seeing:
* I dragged & dropped a file from Finder into a folder in Atom. The folder is under version control with Git
* If I do `Toggle Git Diff Details` on any other file, it works fine (as expected)
* If I try to do `Toggle Git Diff Details` on the file that I just added, I get the exception described above.

**Comment by samu** [comment]
@jmdacruz thanks for the details, i'll try to get some time to fix this
