### ISSUE TITLE
Uncaught TypeError: repo.relativize is not a function

### ISSUE THREAD

**Issue by michael-gracy** [samu/git-diff-details#67]
[Enter steps to reproduce below:]

1. Open git version controlled file.
2. Make a change.
3. Add and commit the change, but don't push.
4. Right-click in open file display and select 'Toggle Git Diff Details' (may have to do more than once to reproduce).

**Atom Version**: 1.12.9
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.6
**Thrown From**: [git-diff-details](https://github.com/samu/git-diff-details) package, v1.4.0

### Stack Trace

Uncaught TypeError: repo.relativize is not a function

```
At /Users/michael.gracy/.atom/packages/git-diff-details/lib/data-manager.coffee:52

TypeError: repo.relativize is not a function
    at DiffDetailsDataManager.module.exports.DiffDetailsDataManager.prepareLineDiffDetails (/Users/michael.gracy/.atom/packages/git-diff-details/lib/data-manager.coffee:52:55)
    at DiffDetailsDataManager.module.exports.DiffDetailsDataManager.updateLineDiffDetails (/Users/michael.gracy/.atom/packages/git-diff-details/lib/data-manager.coffee:39:8)
    at DiffDetailsDataManager.module.exports.DiffDetailsDataManager.getSelectedHunk (/Users/michael.gracy/.atom/packages/git-diff-details/lib/data-manager.coffee:17:8)
    at AtomGitDiffDetailsView.module.exports.AtomGitDiffDetailsView.updateDiffDetailsDisplay (/Users/michael.gracy/.atom/packages/git-diff-details/lib/git-diff-details-view.coffee:135:61)
    at AtomGitDiffDetailsView.module.exports.AtomGitDiffDetailsView.updateDiffDetails (/Users/michael.gracy/.atom/packages/git-diff-details/lib/git-diff-details-view.coffee:58:6)
    at AtomGitDiffDetailsView.module.exports.AtomGitDiffDetailsView.toggleShowDiffDetails (/Users/michael.gracy/.atom/packages/git-diff-details/lib/git-diff-details-view.coffee:62:6)
    at atom-text-editor.<anonymous> (/Users/michael.gracy/.atom/packages/git-diff-details/lib/housekeeping.coffee:25:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/michael.gracy/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/Users/michael.gracy/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/michael.gracy/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Users/michael.gracy/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1142:28)
    at EventEmitter.outerCallback (/Users/michael.gracy/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:332:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:15.2.0 git-plus-context:diff (span.name.icon.icon-file-text)
     -0:00.2.0 git-diff-details:toggle-git-diff-details (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ansible": [
        "yml"
      ]
    },
    "disabledPackages": [
      "language-gfm",
      "dash-on-cursor-active",
      "metrics",
      "whitespace",
      "hyperclick",
      "linter-puppet-lint",
      "linter-markdown",
      "language-powershell",
      "markdown-pdf",
      "markdown-preview-plus",
      "markdown-scroll-sync",
      "markdown-writer"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "*.pyc",
      "*.pyo"
    ],
    "packagesWithKeymapsDisabled": [],
    "projectHome": "/Users/michael.gracy/source",
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.16 (active)
atom-keyboard-macros, v0.9.2 (inactive)
atom-shell-commands, v1.5.0 (active)
autocomplete-ansible, v0.1.10 (active)
autocomplete-bash-builtins, v0.3.4 (active)
autocomplete-json, v5.2.0 (active)
autocomplete-python, v1.8.26 (active)
block-comment, v0.4.3 (inactive)
config-import-export, v0.3.1 (inactive)
dash, v1.7.0 (inactive)
dash-on-cursor-active, v0.1.2 (inactive)
file-types, v0.5.4-p1 (active)
git-blame, v0.4.11 (inactive)
git-diff-details, v1.4.0 (active)
git-plus, v7.0.5 (active)
git-time-machine, v1.5.4 (inactive)
go-debug, v1.0.3 (active)
go-plus, v5.1.0 (active)
go-signature-statusbar, v1.2.0 (active)
gotests, v0.3.0 (active)
hyperclick, v0.0.39 (inactive)
json-colorer, v0.3.0 (active)
json-generator, v0.1.15 (active)
jsonlint, v1.1.4 (active)
language-ansible, v0.1.11 (active)
language-markdown, v0.18.1 (active)
language-powershell, v4.0.0 (inactive)
language-puppet, v0.22.0 (active)
linter, v1.11.18 (active)
linter-ansible-linting, v1.2.1 (active)
linter-checkbashisms, v0.1.5 (active)
linter-markdown, v3.0.2 (inactive)
linter-puppet-lint, v0.8.1 (inactive)
linter-python, v3.0.5 (active)
linter-python-pep8, v0.2.0 (active)
linter-shellcheck, v1.4.2 (inactive)
lipsum, v0.1.0 (inactive)
markdown-pdf, v1.5.0 (inactive)
markdown-preview-plus, v2.4.0 (inactive)
markdown-scroll-sync, v2.1.2 (inactive)
markdown-writer, v2.6.3 (inactive)
overlay-status-icons, v0.1.6 (active)
project-manager, v3.3.3 (active)
python-debugger, v0.1.0 (inactive)
python-indent, v1.0.0 (active)
python-nosetests, v0.2.0 (inactive)
python-tools, v0.6.8 (active)
qolor, v0.4.1 (active)
save-session, v0.15.7 (active)
script, v3.13.0 (inactive)
ssh-config, v0.10.1 (active)
svn, v0.0.13 (active)
terminal-plus, v0.14.5 (active)
tool-bar, v1.0.1 (active)
tool-bar-atom, v1.7.0 (active)
zentabs, v0.8.8 (active)
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by samu** [comment]
Thanks for reporting @michael-gracy. I can't reproduce though :( I'll leave this open and see if anybody else has this problem too.
